<?xml version="1.0" ?>

<robot name="Box" xmlns:xacro="http://www.ros.org/wiki/xacro">



  <xacro:property name="PI" value="3.1415926835897931"/>
  <xacro:property name="base_height" value="1.0639"/>
  <xacro:property name="tyre_x" value="-1.05"/>
  <xacro:property name="tyre_x2" value="-1.55"/>
  <xacro:property name="tyre_y" value="0.765"/>
  <xacro:property name="tyre_length" value="0.229"/>
  <xacro:property name="tyre_r" value="0.66"/>
  <xacro:property name="tyre_radius" value="0.356"/>
  <xacro:property name="car_height" value="1.4478"/>
  <xacro:property name="sensor_box" value="0.25"/>
  <xacro:property name="tyre_height" value="-0.696"/>
  <xacro:property name="str_length" value="0.01"/>
  <xacro:property name="str_radius" value="0.1"/>
  <xacro:property name="str_angle" value="0.05"/>
  <xacro:property name="car_width" value="1.301"/>
  <xacro:property name="tyre_origin">
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${-PI/2}"/>
  </xacro:property>
  <xacro:property name="tyre_origin_2">
        <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
  </xacro:property>
  <xacro:property name="tyre_origin_3">
        <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:property>

        <xacro:include filename="$(find cat_description)/urdf/box.gazebo"/>


<!--Car Body-->

<link name="base_link">
     <collision>
         <origin xyz="0 0 ${base_height}" rpy="0 0 ${-PI/2}"/>
           <geometry>
            <box size="2.62 ${car_width} ${car_height}"/>
        </geometry>
      </collision>

     <visual>
        <origin xyz="0 0 ${base_height + 0.05}" rpy="0 0 ${-PI/2}"/>
        <geometry>
          <mesh filename="package://cat_description/meshes/ford_escape_no_wheels_2.dae"/>
        </geometry>
     </visual>

     <inertial>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <mass value="2000.000000"/>
        <inertia
          ixx="480"  ixy="0.000000" ixz="0.000000"
          iyy="1370" iyz="0.000000"
          izz="1370"/>
      </inertial>
</link>

<!--Back Right Wheel-->




<joint name="back_right_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="back_right_wheel_link"/>
      <origin xyz="${tyre_y} ${-tyre_x} ${tyre_r}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.7"/>
     <limit effort="100" velocity="100" />
      <joint_properties damping="0.0" friction="5.0" />
</joint>

<link name="back_right_wheel_link">
     <collision>
	<xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_3"/>
        <geometry>
          <mesh filename="package://cat_description/meshes/ford_escape_wheel.dae"/>
      <scale xyz="1.2 1 1"/>
        </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>




<!--Back Left Wheel-->




<joint name="back_left_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="back_left_wheel_link"/>
      <origin xyz="${-tyre_y} ${-tyre_x} ${tyre_r}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="100" velocity="100" />
      <joint_properties damping="0.0" friction="5.0" />
</joint>

<link name="back_left_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="0.229" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
        <geometry>
          <mesh filename="package://cat_description/meshes/ford_escape_wheel.dae"/>
          <scale xyz="1.2 1 1"/>
        </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>



<!--Right Steering-->




<joint name="front_right_steering_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_right_steering_link"/>
        <origin xyz="${-car_width/2 - str_length/2} ${tyre_x2}  ${tyre_r}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<link name="front_right_steering_link">
        <collision>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
        </collision>

        <visual>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry> 
        </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>


<!--Right Front Wheel-->




<joint name="front_right_wheel_joint" type="fixed">
      <parent link="front_right_steering_link"/>
      <child link="front_right_wheel_link"/>
      <origin xyz="${-str_length/2 - tyre_length/2} 0 0" rpy="0 0 ${PI}"/>
      <axis xyz="0 1 0"/>
</joint>

<link name="front_right_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
                                     
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_3"/>
        <geometry>
          <mesh filename="package://cat_description/meshes/ford_escape_wheel.dae"/>
        <scale xyz="1.2 1 1"/>
       </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>




<!--Left Steering-->



<joint name="front_left_steering_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_left_steering_link"/>
        <origin xyz="${car_width/2 + str_length/2} ${tyre_x2} ${tyre_r}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<link name="front_left_steering_link">
        <collision>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
        </collision>

        <visual>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
        </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>



<!--Front Right Wheel-->



<joint name="front_left_wheel_joint" type="fixed">
      <parent link="front_left_steering_link"/>
      <child link="front_left_wheel_link"/>
      <origin xyz="${str_length/2 + tyre_length/2} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
</joint>


<link name="front_left_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
               <geometry>
         <cylinder length="0.229" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_3"/>
       <geometry>
          <mesh filename="package://cat_description/meshes/ford_escape_wheel.dae"/>
            <scale xyz="1.2 1 1"/>
       </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>

<!-- Camera-->
<!--


<joint name="camera_joint" type="fixed">
<origin xyz="0 0 ${0.725 + sensor_box/2 + 1.25}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
</joint>

<link name="camera_link">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
          <box size="${sensor_box} ${sensor_box} ${sensor_box}"
/>
          </geometry>
        </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

-->
</robot>
