(cl:in-package torcs_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ANGLE-VAL
          ANGLE
          CURRENTLAPTIME-VAL
          CURRENTLAPTIME
          DAMAGE-VAL
          DAMAGE
          DISTFROMSTART-VAL
          DISTFROMSTART
          DISTRACED-VAL
          DISTRACED
          FUEL-VAL
          FUEL
          GEAR-VAL
          GEAR
          LASTLAPTIME-VAL
          LASTLAPTIME
          RACEPOS-VAL
          RACEPOS
          RPM-VAL
          RPM
          TRACKPOS-VAL
          TRACKPOS
          WHEELSPINVEL-VAL
          WHEELSPINVEL
          Z-VAL
          Z
))