// Generated by gencpp from file motion_planner/srvParkingCmdResponse.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNER_MESSAGE_SRVPARKINGCMDRESPONSE_H
#define MOTION_PLANNER_MESSAGE_SRVPARKINGCMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_planner
{
template <class ContainerAllocator>
struct srvParkingCmdResponse_
{
  typedef srvParkingCmdResponse_<ContainerAllocator> Type;

  srvParkingCmdResponse_()
    : result(0)  {
    }
  srvParkingCmdResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvParkingCmdResponse_

typedef ::motion_planner::srvParkingCmdResponse_<std::allocator<void> > srvParkingCmdResponse;

typedef boost::shared_ptr< ::motion_planner::srvParkingCmdResponse > srvParkingCmdResponsePtr;
typedef boost::shared_ptr< ::motion_planner::srvParkingCmdResponse const> srvParkingCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::motion_planner::srvParkingCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_planner/srvParkingCmdResponse";
  }

  static const char* value(const ::motion_planner::srvParkingCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n\
\n\
\n\
";
  }

  static const char* value(const ::motion_planner::srvParkingCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvParkingCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_planner::srvParkingCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_planner::srvParkingCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_PLANNER_MESSAGE_SRVPARKINGCMDRESPONSE_H
