// Generated by gencpp from file oroca_ros_tutorials/srvTutorial.msg
// DO NOT EDIT!


#ifndef OROCA_ROS_TUTORIALS_MESSAGE_SRVTUTORIAL_H
#define OROCA_ROS_TUTORIALS_MESSAGE_SRVTUTORIAL_H

#include <ros/service_traits.h>


#include <oroca_ros_tutorials/srvTutorialRequest.h>
#include <oroca_ros_tutorials/srvTutorialResponse.h>


namespace oroca_ros_tutorials
{

struct srvTutorial
{

typedef srvTutorialRequest Request;
typedef srvTutorialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvTutorial
} // namespace oroca_ros_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::oroca_ros_tutorials::srvTutorial > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::oroca_ros_tutorials::srvTutorial&) { return value(); }
};

template<>
struct DataType< ::oroca_ros_tutorials::srvTutorial > {
  static const char* value()
  {
    return "oroca_ros_tutorials/srvTutorial";
  }

  static const char* value(const ::oroca_ros_tutorials::srvTutorial&) { return value(); }
};


// service_traits::MD5Sum< ::oroca_ros_tutorials::srvTutorialRequest> should match 
// service_traits::MD5Sum< ::oroca_ros_tutorials::srvTutorial > 
template<>
struct MD5Sum< ::oroca_ros_tutorials::srvTutorialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::oroca_ros_tutorials::srvTutorial >::value();
  }
  static const char* value(const ::oroca_ros_tutorials::srvTutorialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::oroca_ros_tutorials::srvTutorialRequest> should match 
// service_traits::DataType< ::oroca_ros_tutorials::srvTutorial > 
template<>
struct DataType< ::oroca_ros_tutorials::srvTutorialRequest>
{
  static const char* value()
  {
    return DataType< ::oroca_ros_tutorials::srvTutorial >::value();
  }
  static const char* value(const ::oroca_ros_tutorials::srvTutorialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::oroca_ros_tutorials::srvTutorialResponse> should match 
// service_traits::MD5Sum< ::oroca_ros_tutorials::srvTutorial > 
template<>
struct MD5Sum< ::oroca_ros_tutorials::srvTutorialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::oroca_ros_tutorials::srvTutorial >::value();
  }
  static const char* value(const ::oroca_ros_tutorials::srvTutorialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::oroca_ros_tutorials::srvTutorialResponse> should match 
// service_traits::DataType< ::oroca_ros_tutorials::srvTutorial > 
template<>
struct DataType< ::oroca_ros_tutorials::srvTutorialResponse>
{
  static const char* value()
  {
    return DataType< ::oroca_ros_tutorials::srvTutorial >::value();
  }
  static const char* value(const ::oroca_ros_tutorials::srvTutorialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OROCA_ROS_TUTORIALS_MESSAGE_SRVTUTORIAL_H
