set(_CATKIN_CURRENT_PACKAGE "odroid_control_cornering_ed3")
set(odroid_control_cornering_ed3_VERSION "0.0.0")
set(odroid_control_cornering_ed3_MAINTAINER "root <root@todo.todo>")
set(odroid_control_cornering_ed3_PACKAGE_FORMAT "1")
set(odroid_control_cornering_ed3_BUILD_DEPENDS "roscpp" "std_msgs")
set(odroid_control_cornering_ed3_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(odroid_control_cornering_ed3_BUILDTOOL_DEPENDS "catkin")
set(odroid_control_cornering_ed3_BUILDTOOL_EXPORT_DEPENDS )
set(odroid_control_cornering_ed3_EXEC_DEPENDS "roscpp" "std_msgs")
set(odroid_control_cornering_ed3_RUN_DEPENDS "roscpp" "std_msgs")
set(odroid_control_cornering_ed3_TEST_DEPENDS )
set(odroid_control_cornering_ed3_DOC_DEPENDS )
set(odroid_control_cornering_ed3_DEPRECATED "")