# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from model_predictive_navigation/EgoGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EgoGoal(genpy.Message):
  _md5sum = "a8793baddedab0f35d8e3e4d6b9fdc7b"
  _type = "model_predictive_navigation/EgoGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 r
float32 theta
float32 delta
float32 vMax
float32 k1
float32 k2"""
  __slots__ = ['r','theta','delta','vMax','k1','k2']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       r,theta,delta,vMax,k1,k2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EgoGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.r is None:
        self.r = 0.
      if self.theta is None:
        self.theta = 0.
      if self.delta is None:
        self.delta = 0.
      if self.vMax is None:
        self.vMax = 0.
      if self.k1 is None:
        self.k1 = 0.
      if self.k2 is None:
        self.k2 = 0.
    else:
      self.r = 0.
      self.theta = 0.
      self.delta = 0.
      self.vMax = 0.
      self.k1 = 0.
      self.k2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.r, _x.theta, _x.delta, _x.vMax, _x.k1, _x.k2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.r, _x.theta, _x.delta, _x.vMax, _x.k1, _x.k2,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.r, _x.theta, _x.delta, _x.vMax, _x.k1, _x.k2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.r, _x.theta, _x.delta, _x.vMax, _x.k1, _x.k2,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6f = struct.Struct("<6f")
