// Generated by gencpp from file motion_planner_gazebo/srvHeightMap.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNER_GAZEBO_MESSAGE_SRVHEIGHTMAP_H
#define MOTION_PLANNER_GAZEBO_MESSAGE_SRVHEIGHTMAP_H

#include <ros/service_traits.h>


#include <motion_planner_gazebo/srvHeightMapRequest.h>
#include <motion_planner_gazebo/srvHeightMapResponse.h>


namespace motion_planner_gazebo
{

struct srvHeightMap
{

typedef srvHeightMapRequest Request;
typedef srvHeightMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvHeightMap
} // namespace motion_planner_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_planner_gazebo::srvHeightMap > {
  static const char* value()
  {
    return "6f559bfa1f52d42afbe43f629231fbe9";
  }

  static const char* value(const ::motion_planner_gazebo::srvHeightMap&) { return value(); }
};

template<>
struct DataType< ::motion_planner_gazebo::srvHeightMap > {
  static const char* value()
  {
    return "motion_planner_gazebo/srvHeightMap";
  }

  static const char* value(const ::motion_planner_gazebo::srvHeightMap&) { return value(); }
};


// service_traits::MD5Sum< ::motion_planner_gazebo::srvHeightMapRequest> should match 
// service_traits::MD5Sum< ::motion_planner_gazebo::srvHeightMap > 
template<>
struct MD5Sum< ::motion_planner_gazebo::srvHeightMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_planner_gazebo::srvHeightMap >::value();
  }
  static const char* value(const ::motion_planner_gazebo::srvHeightMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_planner_gazebo::srvHeightMapRequest> should match 
// service_traits::DataType< ::motion_planner_gazebo::srvHeightMap > 
template<>
struct DataType< ::motion_planner_gazebo::srvHeightMapRequest>
{
  static const char* value()
  {
    return DataType< ::motion_planner_gazebo::srvHeightMap >::value();
  }
  static const char* value(const ::motion_planner_gazebo::srvHeightMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_planner_gazebo::srvHeightMapResponse> should match 
// service_traits::MD5Sum< ::motion_planner_gazebo::srvHeightMap > 
template<>
struct MD5Sum< ::motion_planner_gazebo::srvHeightMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_planner_gazebo::srvHeightMap >::value();
  }
  static const char* value(const ::motion_planner_gazebo::srvHeightMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_planner_gazebo::srvHeightMapResponse> should match 
// service_traits::DataType< ::motion_planner_gazebo::srvHeightMap > 
template<>
struct DataType< ::motion_planner_gazebo::srvHeightMapResponse>
{
  static const char* value()
  {
    return DataType< ::motion_planner_gazebo::srvHeightMap >::value();
  }
  static const char* value(const ::motion_planner_gazebo::srvHeightMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_PLANNER_GAZEBO_MESSAGE_SRVHEIGHTMAP_H
