// Generated by gencpp from file motion_planner_gazebo/srvParkingCmd.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNER_GAZEBO_MESSAGE_SRVPARKINGCMD_H
#define MOTION_PLANNER_GAZEBO_MESSAGE_SRVPARKINGCMD_H

#include <ros/service_traits.h>


#include <motion_planner_gazebo/srvParkingCmdRequest.h>
#include <motion_planner_gazebo/srvParkingCmdResponse.h>


namespace motion_planner_gazebo
{

struct srvParkingCmd
{

typedef srvParkingCmdRequest Request;
typedef srvParkingCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvParkingCmd
} // namespace motion_planner_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_planner_gazebo::srvParkingCmd > {
  static const char* value()
  {
    return "6f559bfa1f52d42afbe43f629231fbe9";
  }

  static const char* value(const ::motion_planner_gazebo::srvParkingCmd&) { return value(); }
};

template<>
struct DataType< ::motion_planner_gazebo::srvParkingCmd > {
  static const char* value()
  {
    return "motion_planner_gazebo/srvParkingCmd";
  }

  static const char* value(const ::motion_planner_gazebo::srvParkingCmd&) { return value(); }
};


// service_traits::MD5Sum< ::motion_planner_gazebo::srvParkingCmdRequest> should match 
// service_traits::MD5Sum< ::motion_planner_gazebo::srvParkingCmd > 
template<>
struct MD5Sum< ::motion_planner_gazebo::srvParkingCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_planner_gazebo::srvParkingCmd >::value();
  }
  static const char* value(const ::motion_planner_gazebo::srvParkingCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_planner_gazebo::srvParkingCmdRequest> should match 
// service_traits::DataType< ::motion_planner_gazebo::srvParkingCmd > 
template<>
struct DataType< ::motion_planner_gazebo::srvParkingCmdRequest>
{
  static const char* value()
  {
    return DataType< ::motion_planner_gazebo::srvParkingCmd >::value();
  }
  static const char* value(const ::motion_planner_gazebo::srvParkingCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_planner_gazebo::srvParkingCmdResponse> should match 
// service_traits::MD5Sum< ::motion_planner_gazebo::srvParkingCmd > 
template<>
struct MD5Sum< ::motion_planner_gazebo::srvParkingCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_planner_gazebo::srvParkingCmd >::value();
  }
  static const char* value(const ::motion_planner_gazebo::srvParkingCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_planner_gazebo::srvParkingCmdResponse> should match 
// service_traits::DataType< ::motion_planner_gazebo::srvParkingCmd > 
template<>
struct DataType< ::motion_planner_gazebo::srvParkingCmdResponse>
{
  static const char* value()
  {
    return DataType< ::motion_planner_gazebo::srvParkingCmd >::value();
  }
  static const char* value(const ::motion_planner_gazebo::srvParkingCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_PLANNER_GAZEBO_MESSAGE_SRVPARKINGCMD_H
