// Generated by gencpp from file rndf_manager/srvHeightMap.msg
// DO NOT EDIT!


#ifndef RNDF_MANAGER_MESSAGE_SRVHEIGHTMAP_H
#define RNDF_MANAGER_MESSAGE_SRVHEIGHTMAP_H

#include <ros/service_traits.h>


#include <rndf_manager/srvHeightMapRequest.h>
#include <rndf_manager/srvHeightMapResponse.h>


namespace rndf_manager
{

struct srvHeightMap
{

typedef srvHeightMapRequest Request;
typedef srvHeightMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvHeightMap
} // namespace rndf_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rndf_manager::srvHeightMap > {
  static const char* value()
  {
    return "6f559bfa1f52d42afbe43f629231fbe9";
  }

  static const char* value(const ::rndf_manager::srvHeightMap&) { return value(); }
};

template<>
struct DataType< ::rndf_manager::srvHeightMap > {
  static const char* value()
  {
    return "rndf_manager/srvHeightMap";
  }

  static const char* value(const ::rndf_manager::srvHeightMap&) { return value(); }
};


// service_traits::MD5Sum< ::rndf_manager::srvHeightMapRequest> should match 
// service_traits::MD5Sum< ::rndf_manager::srvHeightMap > 
template<>
struct MD5Sum< ::rndf_manager::srvHeightMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rndf_manager::srvHeightMap >::value();
  }
  static const char* value(const ::rndf_manager::srvHeightMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rndf_manager::srvHeightMapRequest> should match 
// service_traits::DataType< ::rndf_manager::srvHeightMap > 
template<>
struct DataType< ::rndf_manager::srvHeightMapRequest>
{
  static const char* value()
  {
    return DataType< ::rndf_manager::srvHeightMap >::value();
  }
  static const char* value(const ::rndf_manager::srvHeightMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rndf_manager::srvHeightMapResponse> should match 
// service_traits::MD5Sum< ::rndf_manager::srvHeightMap > 
template<>
struct MD5Sum< ::rndf_manager::srvHeightMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rndf_manager::srvHeightMap >::value();
  }
  static const char* value(const ::rndf_manager::srvHeightMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rndf_manager::srvHeightMapResponse> should match 
// service_traits::DataType< ::rndf_manager::srvHeightMap > 
template<>
struct DataType< ::rndf_manager::srvHeightMapResponse>
{
  static const char* value()
  {
    return DataType< ::rndf_manager::srvHeightMap >::value();
  }
  static const char* value(const ::rndf_manager::srvHeightMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RNDF_MANAGER_MESSAGE_SRVHEIGHTMAP_H
