// Generated by gencpp from file localization_gazebo/LocalizationData.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_GAZEBO_MESSAGE_LOCALIZATIONDATA_H
#define LOCALIZATION_GAZEBO_MESSAGE_LOCALIZATIONDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localization_gazebo
{
template <class ContainerAllocator>
struct LocalizationData_
{
  typedef LocalizationData_<ContainerAllocator> Type;

  LocalizationData_()
    : heading(0.0)
    , x(0.0)
    , y(0.0)
    , v(0.0)  {
    }
  LocalizationData_(const ContainerAllocator& _alloc)
    : heading(0.0)
    , x(0.0)
    , y(0.0)
    , v(0.0)  {
  (void)_alloc;
    }



   typedef double _heading_type;
  _heading_type heading;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _v_type;
  _v_type v;




  typedef boost::shared_ptr< ::localization_gazebo::LocalizationData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization_gazebo::LocalizationData_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizationData_

typedef ::localization_gazebo::LocalizationData_<std::allocator<void> > LocalizationData;

typedef boost::shared_ptr< ::localization_gazebo::LocalizationData > LocalizationDataPtr;
typedef boost::shared_ptr< ::localization_gazebo::LocalizationData const> LocalizationDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization_gazebo::LocalizationData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization_gazebo::LocalizationData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace localization_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'localization_gazebo': ['/home/dyros-vehicle/gitrepo/lockdpwn/ROS/catkin_ws/src/localization_gazebo/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::localization_gazebo::LocalizationData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization_gazebo::LocalizationData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization_gazebo::LocalizationData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization_gazebo::LocalizationData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization_gazebo::LocalizationData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization_gazebo::LocalizationData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization_gazebo::LocalizationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81dcd86073f3af8543535f8323fd4adc";
  }

  static const char* value(const ::localization_gazebo::LocalizationData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81dcd86073f3af85ULL;
  static const uint64_t static_value2 = 0x43535f8323fd4adcULL;
};

template<class ContainerAllocator>
struct DataType< ::localization_gazebo::LocalizationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization_gazebo/LocalizationData";
  }

  static const char* value(const ::localization_gazebo::LocalizationData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization_gazebo::LocalizationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 heading\n\
float64 x\n\
float64 y\n\
float64 v\n\
";
  }

  static const char* value(const ::localization_gazebo::LocalizationData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization_gazebo::LocalizationData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizationData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization_gazebo::LocalizationData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization_gazebo::LocalizationData_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_GAZEBO_MESSAGE_LOCALIZATIONDATA_H
