
# Summary: 
# This YAML file includes the controller connectivity for ROS-based control
# through Gazebo. For more information and for the tutorials used to create
# this file, see
# http://gazebosim.org/tutorials/?tut=ros_control#Prerequisites

# controls the rear two tires based on individual motors
manycar:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers ---------------------------------------

  # The left/right rear wheels are what moves the car. This
  # controller set uses PID for velocity set points
  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel_joint
    pid: {p: 1000.0, i: 0.001, d: 10.0}
  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_right_wheel_joint
    pid: {p: 1000.0, i: 0.001, d: 10.0}
  front_left_steering_position_controller:
    type: position_controllers/JointPositionController
    joint: front_left_steering_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  front_right_steering_position_controller:
    type: position_controllers/JointPositionController
    joint: front_right_steering_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

